CREATE OR REPLACE TABLE SSI_SAP_TO_SNOW_CLONE.REPORT.SalesOrganizationsMD
(
  Client_MANDT STRING,
  SalesOrg_VKORG STRING,
  SalesOrgCurrency_WAERS STRING,
  SalesOrgCustomer_KUNNR STRING,
  CompanyCode_BUKRS STRING,
  Country_LAND1 STRING,
  CoCoCurrency_WAERS STRING,
  FiscalYrVariant_PERIV STRING,
  Company_BUTXT STRING,
  SalesOrgName_VTEXT STRING,
  Language_SPRAS STRING
);

INSERT INTO SSI_SAP_TO_SNOW_CLONE.REPORT.SalesOrganizationsMD
SELECT
    TVKO.MANDT AS Client_MANDT,
    TVKO.VKORG AS SalesOrg_VKORG,
    TVKO.WAERS AS SalesOrgCurrency_WAERS,
    TVKO.KUNNR AS SalesOrgCustomer_KUNNR,
    TVKO.BUKRS AS CompanyCode_BUKRS,
    T001.LAND1 AS Country_LAND1,
    T001.WAERS AS CoCoCurrency_WAERS,
    T001.PERIV AS FiscalYrVariant_PERIV,
    T001.BUTXT AS Company_BUTXT,
    TVKOT.VTEXT AS SalesOrgName_VTEXT,
    TVKOT.SPRAS AS Language_SPRAS
  FROM
    SSI_SAP_TO_SNOW_CLONE.RAW.TVKO AS TVKO
  LEFT OUTER JOIN
    SSI_SAP_TO_SNOW_CLONE.RAW.T001 AS T001
    ON
      TVKO.MANDT = T001.MANDT
      AND TVKO.BUKRS = T001.BUKRS
  INNER JOIN
    SSI_SAP_TO_SNOW_CLONE.RAW.TVKOT AS TVKOT
    ON
      TVKO.MANDT = TVKOT.MANDT
      AND TVKO.VKORG = TVKOT.VKORG